export const CHANGE_DISPLAY = 'DISPLAY-TYPE/CHANGE_DISPLAY'
export const FETCH_REPOSITORIES = 'REPOSITORIES-LIST/FETCH_REPOSITORIES'
export const ADD_ITEM_MY_LIST = 'REPOSITORIES-LIST/ADD_ITEM_MY_LIST'
export const DEL_ITEM_MY_LIST = 'REPOSITORIES-LIST/DEL_ITEM_MY_LIST'
